name              'bot-trainer'
maintainer        'Sous Cherfffss'
maintainer_email  'fire@sous-chefs.org'
license           'Apache-2.0'
description       'Do not use, Sous-Chefs cookbook for testing only!'
version           '0.1.2'
source_url        'https://github.com/sous-chefs/bot-trainer'
issues_url        'https://github.com/sous-chefs/bot-trainer/issues'
chef_version      '>= 16'

supports 'centos'
supports 'debian'
supports 'mac_os_x'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
supports 'windows'
