---
name: 'Check Metadata'

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  check-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Metadata
        uses: damacus/check-chef-metadata-action@main
        with:
          maintainer: 'Bob'
